ants_view = 4  # میزان دید منهتنی نیروها
ants_reg_rate = 0.8  # مقدار منبع به جا مانده بعد از مرگ نیرو
base_range = 6  # میزان دید منهتنی پایگاه
base_damage = 3  # میزان آسیب حمله پایگاه
base_health = 20  # میزان سلامتی اولیه پایگاه
max_com_per_turn = 5  # حداکثر تعداد پیام در هر دور
max_com_length = 32  # (Byte)حداکثر طول پیام‌ها
max_turn = 100  # حداکثر تعداد دور بازی
worker_health = 6  # میزان سلامتی اولیه مورچه (کارگر)
attacker_health = 8  # میزان سلامت اولیه عقرب (سرباز)
attacker_range = 4  # برد حمله عقرب
attacker_damage = 2  # میزان آسیب حمله عقرب
worker_price = 10  # هزینه تولید مورچه
ant_max_rec_amount = 10  # میزان باری که مورچه می‌تواند حمل کند
attacker_price = 15  # هزینه تولید عقرب
start_worker = 4  # تعداد مورچه‌ها در شروع
start_attacker = 0  # تعداد عقرب‌ها در شروع
max_turn_time = 0.1  # زمان هر نوبت
map_size = 35  # حداکثر طول هر ضلع نقشه
map_wall_perc = 20  # % درصدی از مپ که دیوارها هستند
min_base_dist = 10  # حداقل فاصله‌ی دو پایگاه
work_rec_amount = 800  # مقدار گندم موجود در نقشه
attack_rec_amount = 800  # مقدار علف موجود در نقشه
mirror_effect = True  # اتصال بالا و پایین و چپ راست زمین
